export const STACKABLE_DEFAULT = 'STACKABLE_DEFAULT';
export const STACKABLE_STONE = 'STACKABLE_STONE';
export const STACKABLE_ASH = 'STACKABLE_ASH';
export const STACKABLE_GLASS_SHARD = 'STACKABLE_GLASS_SHARD';
