export const AREA_TYPE_WATER = 'AREA_TYPE_WATER';
export const AREA_TYPE_PLAINS = 'AREA_TYPE_PLAINS';
export const AREA_TYPE_FOREST = 'AREA_TYPE_FOREST';
export const AREA_TYPE_DESERT = 'AREA_TYPE_DESERT';
export const AREA_TYPE_CANYON = 'AREA_TYPE_CANYON';
